NewsPaper/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    # Делаем так, чтобы все адреса из нашего приложения (simpleapp/urls.py)
    # подключались к главному приложению с префиксом products/.
    path('news/', include('simpleapp.urls')),
    path('', include('protect.urls')),
    path('sign/', include('sign.urls')),
    path('accounts/', include('allauth.urls')),
    path('appointments/', include('appointments.urls')),
    path('accounts/', include('allauth.urls')),
]

news/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .views import CategoryListView
from .views import (PostsList, PostDetail, Posts, PostCreateView, PostUpdateView, PostDeleteView, upgrade_me,
                    subscribe)

app_name = 'news'
#  запрос на сервере = NEWS: post_detail


urlpatterns = [
    path('', Posts.as_view()),
    path('<int:pk>', PostDetail.as_view(), name='post_detail'),
    path('search', PostsList.as_view()),
    path('add', PostCreateView.as_view(), name='post_create'),
    path('<int:pk>/edit', PostUpdateView.as_view(), name='post_update'),
    path('<int:pk>/delete', PostDeleteView.as_view(), name='post_delete'),
    path('upgrade/', upgrade_me, name='upgrade'),
    path('categories/<int:pk>', CategoryListView.as_view(), name='category_list'),
    path('categories/<int:pk>/subscribe', subscribe, name='subscribe'),
    path('posts/<int:pk>', cache_page(60 * 1)(PostsList.as_view()), name='post_list'),
]

news/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import Sum


# импорт базы данных
# импорт django-регистрации
# импорт метода сумма
# коллекцию вызываемых validators для использования с полями модели и формы (лайк и дизлайк)


class Author(models.Model):
    # модель автор
    authorUser = models.OneToOneField(User, on_delete=models.CASCADE, related_name='authors')
    # регистрация пользователя
    ratingAuthor = models.SmallIntegerField(default=0)

    # рейтинг пользователя (автор)

    def update_rating(self):
        # функция обновление рейтинга
        postRat = self.post_set.aggregate(postRating=Sum('rating'))
        # рейтинг публикации
        pRat = 0
        # счетчик по умолчанию
        pRat += postRat.get('postRating')
        # обновление рейтинга
        commentRat = self.authorUser.comment_set.aggregate(commentRating=Sum('rating'))
        # рейтинг комментария
        cRat = 0
        # счетчик по умолчанию
        cRat += commentRat.get('commentRating')
        # обновление рейтинга

        self.ratingAuthor = pRat * 3 + cRat
        self.save()
        # суммарный рейтинг статьи автора умножается на 3

    def __str__(self):
        # method принимает в качестве аргумента только self
        return f'{self.authorUser.username}'
        # выводит имя пользователя (автора)


class Category(models.Model):
    # модель категория
    name = models.CharField(max_length=64, unique=True)
    # поле название с ограничениями (длина=64, уникальное)
    subscribers = models.ManyToManyField(User, max_length=64, blank=True, related_name='categories')

    # subscribers = models.ManyToManyField(User, null=True, blank=True, related_name='categories')
    # связь многие ко многим с моделью пользователь

    def __str__(self):
        return f'{self.name}'
        # return self.name


class Post(models.Model):
    # модель публикация
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    # поле автор+ связь один ко многим

    NEWS = 'NW'
    ARTICLE = 'AR'
    CATEGORY_CHOICES = (
        (NEWS, 'Новость'),
        (ARTICLE, 'Статья'),
    )
    # переменные новости, статья, выбор категории,

    categoryType = models.CharField(max_length=2, choices=CATEGORY_CHOICES, default=ARTICLE)
    # поле выбор категории
    dateCreation = models.DateTimeField(auto_now_add=True)
    # дата публикации
    postCategory = models.ManyToManyField(Category, through='PostCategory')
    # поле категории публикации
    title = models.CharField(max_length=128)
    # заголовок
    text = models.TextField()
    # текст
    rating = models.SmallIntegerField(default=0)

    # рейтинг публикации

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()
        # метод лайк и дизлайк

    def preview(self):
        return self.text[0:123] + '...'
        # метод preview() модели Post, который возвращает начало статьи

    def get_absolute_url(self):
        return f'/news/{self.id}'
        # добавим абсолютный путь, чтобы после создания нас перебрасывало на страницу с товаром

    def __str__(self):
        return f'{self.categoryType.CATEGORY_CHOICES}'
        # выбор категории


class PostCategory(models.Model):
    # промежуточная модель категория публикации (связь один ко многим)
    postThrough = models.ForeignKey(Post, on_delete=models.CASCADE)
    # поле публикации (связь один ко многим)
    categoryThrough = models.ForeignKey(Category, on_delete=models.CASCADE)
    # поле категории (связь один ко многим)


class Comment(models.Model):
    # модель комментарий
    commentPost = models.ForeignKey(Post, on_delete=models.CASCADE)
    # комментарий публикации
    commentUser = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')
    # комментарий пользователя
    text = models.TextField()
    # текст комментария
    dateCreating = models.DateTimeField(auto_now_add=True)
    # дата добавления комментария
    rating = models.SmallIntegerField(default=0)

    # рейтинг комментария

    def like(self):
        self.rating += 1
        self.save()
        # лайк комментария

    def dislike(self):
        self.rating -= 1
        self.save()
        # дизлайк комментария

# python manage.py shell
# from news.models import *
#
# 1 quest Создаем пользователей:
# u1 = User.objects.create_user(username='Иванов Иван Иванович')
# u1
# u2 = User.objects.create_user(username='Петров Петр Петрович')
# u2
# u3 = User.objects.create_user(username='Максимов Максим Максимович')
# u3
# u4 = User.objects.create_user(username='Калинкин Константин Владимирович')
#
# Создаем авторов:
# Author.objects.create(authorUser=u1)
# result: <Author: Author object (1)>
# Author.objects.create(authorUser=u2)
# result: <Author: Author object (2)>
#
# Создаем категории:
#   >>> Category.objects.create(name='IT')
# 	<Category: Category object (1)>
# 	>>> Category.objects.create(name='Sport')
# 	<Category: Category object (2)>
# 	>>> Category.objects.create(name='Politics')
# 	<Category: Category object (3)>
# 	>>> Category.objects.create(name='Education')
# 	<Category: Category object (4)>
# 	>>> Category.objects.create(name='Finance')
# 	<Category: Category object (5)>
#
# Получаем автора по id:
#   >>> author = Author.objects.get(id=1)
# 	>>> author
# 	<Author: Author object (1)>
# 	>>> author2 = Author.objects.get(id=2)
# 	>>> author2
# 	<Author: Author object (2)>
#
# Создаем пост:
#   >>> Post.objects.create(author=author, categoryType='NW', title='Восстание человека', text='Как обойти ИИ и стать умнее? На этот вопрос ответит издательство от SkillFactory!')
# 	<Post: Post object (1)>
# 	>>> Post.objects.get(id=1).title # Post.objects.get(id=1).text
# 	'Восстание человека'
# 	>>> Post.objects.create(author=author, categoryType='AR', title='Workout', text='Make sport is very healthy')
# 	<Post: Post object (2)>
# 	>>> Post.objects.create(author=author2, categoryType='AR', title='Python', text='Hello world!')
# 	<Post: Post object (3)>
#
# К статьям/новостям присваиваем категории:
#
#   >>> Post.objects.get(id=1).postCategory.add(Category.objects.get(id=1))
# 	>>> Post.objects.get(id=2).postCategory.add(Category.objects.get(id=2))
# 	>>> Post.objects.get(id=3).postCategory.add(Category.objects.get(id=1))
# 	>>> Post.objects.get(id=1).postCategory.add(Category.objects.get(id=3))
# 	>>> Post.objects.get(id=2).postCategory.add(Category.objects.get(id=4))
# 	>>> Post.objects.get(id=3).postCategory.add(Category.objects.get(id=3))
#
# Создаем комментарии к статьям/новостям:
# 	>>> Comment.objects.create(commentPost=Post.objects.get(id=1), commentUser=Author.objects.get(id=1).authorUser, text='Greate post')
# 	<Comment: Comment object (1)>
# 	>>> Comment.objects.create(commentPost=Post.objects.get(id=1), commentUser=Author.objects.get(id=2).authorUser, text='Interesting news')
# 	<Comment: Comment object (2)>
# 	>>> Comment.objects.create(commentPost=Post.objects.get(id=2), commentUser=Author.objects.get(id=2).authorUser, text='Get over yourself')
# 	<Comment: Comment object (3)>
# 	>>> Comment.objects.create(commentPost=Post.objects.get(id=3), commentUser=Author.objects.get(id=1).authorUser, text='Python is the best computer program')
# 	<Comment: Comment object (4)>
# 	>>> Comment.objects.create(commentPost=Post.objects.get(id=3), commentUser=Author.objects.get(id=2).authorUser, text='Hello Skillfactory')
# 	<Comment: Comment object (5)>
#
# Применяем функции like() и dislike() к комментариям:
#
#   >>> Comment.objects.get(id=1).like()
# 	>>> Comment.objects.get(id=1).rating
# 	1
# 	>>> Comment.objects.get(id=1).dislike()
# 	>>> Comment.objects.get(id=1).dislike()
# 	>>> Comment.objects.get(id=1).dislike()
# 	>>> Comment.objects.get(id=1).rating
# 	-2
# 	>>> Comment.objects.get(id=2).like()
# 	>>> Comment.objects.get(id=2).like()
# 	>>> Comment.objects.get(id=2).like()
# 	>>> Comment.objects.get(id=3).like()
# 	>>> Comment.objects.get(id=3).like()
# 	>>> Comment.objects.get(id=4).like()
# 	>>> Comment.objects.get(id=5).dislike()
#
# Применяем функции like() и dislike() к статьям/новостям:
#   >>> Post.objects.get(id=1).like()
# 	>>> Post.objects.get(id=1).rating
# 	1
# 	>>> Post.objects.get(id=1).like()
# 	>>> Post.objects.get(id=1).like()
# 	>>> Post.objects.get(id=1).like()
# 	>>> Post.objects.get(id=1).like()
# 	>>> Post.objects.get(id=1).like()
# 	>>> Post.objects.get(id=2).like()
# 	>>> Post.objects.get(id=2).like()
# 	>>> Post.objects.get(id=2).like()
# 	>>> Post.objects.get(id=3).like()
# 	>>> Post.objects.get(id=3).like()
# 	>>> Post.objects.get(id=3).like()
# 	>>> Post.objects.get(id=3).like()
# 	>>> Post.objects.get(id=3).like()
# 	>>> Post.objects.get(id=3).like()
# 	>>> Post.objects.get(id=3).like()
# 	>>> Post.objects.get(id=3).like()
# 	>>> Post.objects.get(id=3).dislike()
# 	>>> Post.objects.get(id=1).dislike()
# 	>>> Post.objects.get(id=1).dislike()
#
# Создал комментарии для User id 3 и 4:
#   >>> Comment.objects.create(commentPost=Post.objects.get(id=3), commentUser=User.objects.get(id=3), text='Hello Skillfactory')
# 	<Comment: Comment object (6)>
# 	>>> Comment.objects.create(commentPost=Post.objects.get(id=1), commentUser=User.objects.get(id=4), text='An interesting question')
# 	<Comment: Comment object (7)>
#
# Применяем функции like() и dislike() к этим комментариям:
# 	>>> Comment.objects.get(id=6).like()
# 	>>> Comment.objects.get(id=7).like()
#
# Получаем автора по id:
# 	>>> Author.objects.get(id=1)
# 	<Author: Author object (1)>
#
# Присваиваем в переменную а и b и обновляем рейтинги пользователей:
# 	>>> a = Author.objects.get(id=1)
# 	>>> a.update_rating()
# 	>>> a.ratingAuthor
# 	18
# 	>>> b = Author.objects.get(id=2)
# 	>>> b.update_rating()
# 	>>> b.ratingAuthor
# 	26
#
# Выводим рейтинг лучшего пользователя применяя сортировку:
# 	>>> a = Author.objects.order_by('-ratingAuthor')[:1]
# 	>>> a
# 	<QuerySet [<Author: Author object (2)>]>
#

news/forms.py
from email.headerregistry import Group

from allauth.account.forms import SignupForm
from django.forms import ModelForm, BooleanField

from .models import Post


# Создаём модельную форму
class PostForm(ModelForm):
    check_box = BooleanField(label='text')  # или же true-false поле

    # в класс мета, как обычно, надо написать модель, по которой будет строится форма и нужные нам поля. Мы уже делали что-то похожее с фильтрами.

    class Meta:
        model = Post
        fields = ['title', 'text', 'author', 'categoryType', 'check_box']


class BasicSignupForm(SignupForm):

    def save(self, request):
        user = super(BasicSignupForm, self).save(request)
        basic_group = Group.objects.get(name='common')
        basic_group.user_set.add(user)
        # ДОБЫВИТЬ ПРИВЕДСТВЕННОЕ ПИСЬМО ТУТ
        return user

news/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.models import Group
from django.core.cache import cache
from django.shortcuts import redirect
from django.shortcuts import render, get_object_or_404
from django.views.decorators.cache import cache_page
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from .filters import PostFilter
from .forms import PostForm
from .models import Post, Category


# импортируем декоратор для кэширования отдельного представления


@cache_page(60 * 5)
# В аргументы к декоратору передаём количество секунд, которые хотим,
# чтобы страница держалась в кэше. Внимание! Пока страница находится в кэше,
# изменения, происходящие на ней, учитываться не будут!
def my_view(request):
    ...


class PostsList(ListView):
    model = Post
    template_name = 'posts_list.html'
    context_object_name = 'posts.html'
    ordering = [' -created_at']
    paginate_by = 2


class PostDetail(DetailView):
    template_name = 'news/post_detail.html'
    queryset = Post.objects.all()

    def get_object(self, *args, **kwargs):
        print(self.request.user.id)
        obj = cache.get(f'post-{self.kwargs["pk"]}', None)
        if not obj:
            obj = super().get_object(queryset=self.queryset)
            cache.set(f'post-{self.kwargs["pk"]}', obj)

        return obj


# def get_context_data(self, **kwargs):
# context = super().get_context_data(**kwargs)
# subscribers = []
# for category in kwargs['object'].category.all():
#     subscribers += category.subscribers.all()
# user = User.objects.filter(pk=self.request.user.pk).first() if self.request.user else None
# context['need_subscribed'] = user not in subscribers
# return context


class PostCreateView(PermissionRequiredMixin, CreateView):
    permission_required = ('news.add_post',)
    template_name = 'news/post_create.html'
    form_class = PostForm


class Posts(LoginRequiredMixin, ListView):
    model = Post
    template_name = 'posts.html.html'
    context_object_name = 'posts.html'
    ordering = [' -created_at']
    paginate_by = 2

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = PostFilter(self.request.GET, queryset=self.get_queryset())
        context['is_not_author'] = not self.request.user.groups.filter(name='authors').exisits()
        return context


class PostUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    permission_required = ('news.change_post',)
    template_name = 'news/post_create.html'
    form_class = PostForm

    def get_object(self, **kwargs):
        id = self.kwargs.get('pk')
        return Post.objects.get(pk=id)


class PostDeleteView(DeleteView):
    template_name = 'news/post_delete.html'
    queryset = Post.objects.all()
    success_url = '/news/'


@login_required
def upgrade_me(request):
    user = request.user
    premium_group = Group.objects.get(name='authors')
    if not request.user.groups.filter(name='authors').exists():
        premium_group.user_set.add(user)
    return redirect('/news')


class CategoryListView(Posts):
    model = Post
    template_name = 'news/category_list.html'
    context_object_name = 'category_news_list'

    def get_queryset(self):
        self.category = get_object_or_404(Category, id=self.kwargs['pk'])
        queryset = Post.objects.filter(category=self.category).order_by('-crated_at')
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_not_subscriber'] = self.request.user not in self.category.subscribers.all()
        context['category'] = self.category
        return context


@login_required
def subscribe(request, pk):
    user = request.user
    category = Category.objects.get(id=pk)
    category.subscribers.add(user)

    message = 'Вы успешно подписались на рассылку новостей категории'
    return render(request, 'news/subscribe.html', {'category': category, 'message': message})

## news : /post_detail.html/post_delete.html/post_create.html/category_list.html
## templates: /posts.html.html/post.html/posts_list.html/base.html

templates/news/base.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block head_title %}{% endblock head_title %}</title>
</head>
<body>
{% block body %}
{% block content %}
{% endblock content %}
{% endblock body %}
{% block extra_body %}
{% endblock extra_body %}
</body>
</html>

templates/news/category_list.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}

{% block title %}
Новости
{% endblock title %}

{% block content %}
{% if is_not_subscriber %}
<p class="text-center"><a class="btn btn-secondary btn-sm" href="{% url 'subscribe' category.id %}">Подписаться</a></p>
{% endif %}
{% if is_not_author%}
<button><a href="{% url 'upgrade' %}">Стать автором</a></button>
{% endif %}
<h1>Список новостей: </h1>
<hr>
{% if category_name_list %}
<form method="GET">
    {{ filter.form }}
    <input type="sumbit" value="Найти">
</form>
<table>
    <tr>
        <td>
            Заголовок
        </td>
        <td>
            Категории
        </td>
        <td>
            Текст
        </td>
        <td>
            Дата
        </td>
    </tr>
    {% for post in category_news_list %}
    <tr>
        <td>
            <a href="{%url 'post_detail' post.id %}">{{ post.title | censor}}</a>
            <a href="{%url 'post_update' post.id %}"><u>Редактировать</u></a>
            <a href="{%url 'post_delete' post.id %}"><u>Удалить</u></a>
        </td>
        <td>
            {% for category in post.category.all %}
            <a href="{%url 'category_list' category.id %}">{{ category }}</a>
            {% endfor %}
        </td>
        <td>
            {{ post.preview | censor }}
        </td>
        <td>
            {{ post.created_at | date:'d M Y' }}
        </td>
    </tr>
    {% endfor %}
</table>
{% else %}
<h2>Новостей нет!</h2>
{% endif %}

<a href="{%url 'post_create' %}">Добавить новую статью</a> </br>

{% if is_paginated %}
{% if page_obj.has_previous %}
<a href="?page=1">First</a>
<a href="?page={{ page_obj.previous.page_number }}"><<<</a>
{% endif %}

{% for num in page_obj.paginator.page_range %}
{% if page_obj.number == num %}
<a>{{ num }}</a>
{% elif num > page_obj.number|add '-3' and num < page_obj.number|add:'3' %}
<a href="?page={{ num }}">{{ num }}</a>
{% endif%}
{% endfor %}

{% if page_obj.has_next %}
<a href="?page={{ page_obj.next_page_number }}">>>></a>
<a href="?page={{ page_obj.paginator.num_pages }}">Last</a>
{% endif %}
{% endif %}

{% endblock content %}

templates/news/daily_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Уведомление</title>
</head>
<body>
<h2>Здравствуйте! Новые статьи за последнюю неделю</h2>
<ul>
    {% for post in posts %}
    <li><a href="{{ link }}{{ post.get_absolute_url }}">{{ post.title }}</a></li>
    {% endfor %}
</ul>
</body>
</html>

templates/news/default.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport"/>
    <meta content="" name="description"/>
    <meta content="" name="author"/>
    <title>Новостной портал</title>
    {% load static %}
    <link href="assets/favicon.ico" rel="icon" type="image/x-icon"/>
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet"/>
</head>
<body>
<!-- Responsive navbar-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="#">Start Bootstrap</a>
        <button aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
                class="navbar-toggler"
                data-bs-target="#navbarSupportedContent" data-bs-toggle="collapse" type="button"><span
                class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item"><a aria-current="page" class="nav-link active" href="#">Home</a></li>
                <li class="nav-item"><a class="nav-link" href="#">Link</a></li>
                <li class="nav-item dropdown">
                    <a aria-expanded="false" class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#"
                       id="navbarDropdown" role="button">Dropdown</a>
                    <ul aria-labelledby="navbarDropdown" class="dropdown-menu dropdown-menu-end">
                        <li><a class="dropdown-item" href="#">Action</a></li>
                        <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li>
                            <hr class="dropdown-divider"/>
                        </li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>
<!-- Page content-->
<div class="container">
    <div class="text-center mt-5">
        <h1>News Portal</h1>
        <p class="lead">Сайт в стадии разработки</p>
        <p>Версия 1.0</p>
    </div>
</div>
{% block content %}
{% endblock content %}
</body>
</html>

templates/news/post.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

{% block title %}
Post
{% endblock title %}

{% block content %}
<h1>Название - {{ post.title| Censor }}</h1>
<p>Текст - {{ post.text | Censor}}</p>
<p>Автор - {{ post.Author.userName }}</p>
<p>Тип - {{ post.get_categoryType_display }}</p>
<h5> Подписка на все категории новостей: </h5>
{% if post.postCategory.all %}
{% for cat in post.postCategory.all %}

<button><a href="{% url 'add_subscribe' cat.id %}">{{ cat.name }}</a></button>
{% endfor %}
{% else %}
У новости нет категорий
{% endif %}
<p>Рейтинг - {{ post.rating }}</p>
<p>Дата загрузки - {{ post.dateCreation }}</p>

<a href="{% url 'post_update' new.id %}"><u>Редактировать</u></a> <!-- добавим ссылку на редактирование товара-->
<a href="{% url 'post_delete' new.id %}"><u> Удалить </u></a> <!-- добавим ссылку на удаление товара-->

{% endblock content %}

templates/news/post_create.html
{%extends 'default.html'%}

{% block content %}
<h1>Создание новости</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save"/>
</form>
{% endblock content %}

templates/news/post_created_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Уведомление</title>
</head>
<body>
<h2>Здравствуйте! Новая <a href="{{ link }}">статья</a> в вашем любимом разделе! </h2>
<p>{{ text }}</p>
</body>
</html>

templates/news/post_delete.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

{% block title %}
Delete
{% endblock title %}

{% block content %}
<h2>Вы действительно хотите удалить данный пост?</h2>
<h1>Название - {{ new.title| Censor }}</h1>
<p>Текст - {{ post.text | Censor}}</p>
<p>Автор - {{ post.Author.userName }}</p>
<p>Дата загрузки - {{ post.dateCreation }}</p>

<form method="POST">
    {% csrf_token %}
    <input type="submit" value="подтвердить"></form>
{% endblock content %}

templates/news/post_detail.html
{%extends 'default.html'%}
{% load custom_filters %}

<head>
    <meta charset="UTF-8">
    <title>Post</title>
</head>
<body>
{% block content %}
<h1>{{ post }}</h1>
<table>
    <tr>
        <td><u>Заголовок</u></td>
        <td><u>Дата публикации</u></td>
        <td><u>Содержание</u></td>
    </tr>
    <tr>
        <td>{{ post.header|censor }}</td>
        <td>{{ post.creation_date|date:'d M Y' }}</td>
        <td>{{ post.text|censor}}</td>
    </tr>
</table>
{% endblock content %}
</body>
</html>

templates/news/post_update.html
{%extends 'default.html'%}

{% block content %}
<h1>Редактирование новости</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save"/>
</form>
{% endblock content %}

templates/news/posts.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}

{% block title %}
Новости
{% endblock title %}

{% block content %}
{% if is_not_author%}
<button><a href="{% url 'upgrade' %}">Стать автором</a></button>
{% endif %}
<h1>Список новостей: </h1>
<hr>
{% if posts %}
<form method="GET">
    {{ filter.form }}
    <input type="sumbit" value="Найти">
</form>
<table>
    <tr>
        <td>
            Заголовок
        </td>
        <td>
            Категории
        </td>
        <td>
            Текст
        </td>
        <td>
            Дата
        </td>
    </tr>
    {% for post in filter.qs %}
    <tr>
        <td>
            <a href="{%url 'post_detail' post.id %}">{{ post.title | censor}}</a>
            <a href="{%url 'post_update' post.id %}"><u>Редактировать</u></a>
            <a href="{%url 'post_delete' post.id %}"><u>Удалить</u></a>
        </td>
        <td>
            {% for category in post.category.all %}
            <a href="{%url 'category_list' category.id %}">{{ category }}</a>
            {% endfor %}
        </td>
        <td>
            {{ post.preview | censor }}
        </td>
        <td>
            {{ post.created_at | date:'d M Y' }}
        </td>
    </tr>
    {% endfor %}
</table>
{% else %}
<h2>Новостей нет!</h2>
{% endif %}

<a href="{%url 'post_create' %}">Добавить новую статью</a> </br>

{% if is_paginated %}
{% if page_obj.has_previous %}
<a href="?page=1">First</a>
<a href="?page={{ page_obj.previous.page_number }}"><<<</a>
{% endif %}

{% for num in page_obj.paginator.page_range %}
{% if page_obj.number == num %}
<a>{{ num }}</a>
{% elif num > page_obj.number|add '-3' and num < page_obj.number|add:'3' %}
<a href="?page={{ num }}">{{ num }}</a>
{% endif%}
{% endfor %}

{% if page_obj.has_next %}
<a href="?page={{ page_obj.next_page_number }}">>>></a>
<a href="?page={{ page_obj.paginator.num_pages }}">Last</a>
{% endif %}
{% endif %}

{% endblock content %}

templates/news/subscribe.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1 class="text-center">{{ message }} {{ category }}</h1>
{% endblock %}